#!/bin/bash

#1.13よりあとのバージョンなら下記コマンドでOK
#docker system prune

#<=1.12の場合
docker rm `docker ps -f "status=exited" -q`
docker rmi `docker images -q`
docker rmi `docker images -f "dangling=true" -q`
docker volume rm `docker volume ls -q`
docker network rm `docker network ls -q`
